### ISSUE TITLE
Tests do not rollback

### ISSUE THREAD

**Issue by joubu** [tomascohen/koha-testing-docker#30]
KOHA_NO_TABLE_LOCKS needs to be set, to avoid LOCK (rollback will fail)
From Koha code:
    my $do_not_lock = ( exists $ENV{_} && $ENV{_} =~ m|prove| ) || $ENV{KOHA_NO_TABLE_LOCKS};

$ENV{_} equals "koha-shell", not the expected "prove"

**Comment by tomascohen** [comment]
Thanks!
